# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none
pr: none
schedules:
- cron: "0 12 * * *"
  displayName: ios specific tests
  branches:
    include:
    - develop
  always: true

pool:
  name: rakeshagent

variables:
#- group: Reporting
- name: NODE_VERSION
  value: 19.6.0

stages:
  - stage: mobileApp_test
    jobs:
      - job: e2e_tests
        timeoutInMinutes: 300
        steps:
          - checkout: self
            clean: true
          - task: NodeTool@0
            displayName: Use Node $(NODE_VERSION)
            inputs:
              versionSpec: $(NODE_VERSION)
          - task: UniversalPackages@0
            displayName: 'Download iOS App'
            inputs:
              command: 'download'
              downloadDirectory: '$(Build.SourcesDirectory)/apps'
              feedsToUse: 'internal'
              vstsFeed: '148fd1d6-b41a-476a-bb5e-afc1eca1d876'
              vstsFeedPackage: 'b9727e46-d93e-48f9-bc0a-5b1f23d4b7db'
              vstsPackageVersion: '*'
          - task: Bash@3
            displayName: Install test-result-reporter
            inputs:
              targetType: 'inline'
              script: npm i test-results-reporter
              workingDirectory: '$(Build.SourcesDirectory)'
          - task: Bash@3
            displayName: Install node dependencies
            inputs:
              targetType: 'inline'
              script: npm install
              workingDirectory: '$(Build.SourcesDirectory)'
          - task: Bash@3
            displayName: Start Appium
            inputs:
              targetType: 'inline'
              script: 'appium --allow-insecure chromedriver_autodownload --base-path /wd/hub'
          - task: Bash@3
            displayName: run ios specific tests
            inputs:
              targetType: 'inline'
              script: 'npm run ios.cucumber.app'
              workingDirectory: '$(Build.SourcesDirectory)'
            continueOnError: true
          - task: PublishPipelineArtifact@1
            displayName: Publish pipeline artifacts
            inputs:
              targetPath: $(System.DefaultWorkingDirectory)/reports
              artifactName: Reports
            continueOnError: true
          - task: PublishTestResults@2
            displayName: 'Publish Test Results'
            inputs:
              testResultsFiles: $(Build.SourcesDirectory)/reports/singleHtml/JunitResults.xml
              failTaskOnFailedTests: true
              testRunTitle: 'Mobile Test Results'
            continueOnError: true